NUMPY

In [ ]:
import numpy as np
#perbedaan list dan array
list = [[1,2,3],[4,5,6],[7,8,9]]
print(f"Ini adalah list: {list}")
print(f"Ini adalah array: {np.array(list)}")

#regenerate array dengan arange => otomatis
print(f"Array dengan arange: {np.arange(0,10)}") #0-9 tanpa jarak
print(f"Array dengan arange: {np.arange(0,10,2)}") #0-9 dengan jarak 2

#regenerate array dengan zeros 
print(f"Array dengan zeros: {np.zeros(5)}") #5 angka 0
print(f"Array dengan zeros: {np.zeros((3,3))}") #3x3 angka 0

#regenerate array dengan ones
print(f"Array dengan ones: {np.ones(5)}") #5 angka 1
print(f"Array dengan ones: {np.ones((3,3))}") #3x3 angka 1

#regenerate array dengan linspace => otomatis
print(f"Array dengan linspace: {np.linspace(0,10,100)}") #0-10 dengan 100 angka

#Identity matrix
np.eye(5)


Ini adalah list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Ini adalah array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array dengan arange: [0 1 2 3 4 5 6 7 8 9]
Array dengan arange: [0 2 4 6 8]
Array dengan zeros: [0. 0. 0. 0. 0.]
Array dengan zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array dengan ones: [1. 1. 1. 1. 1.]
Array dengan ones: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array dengan linspace: [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.050505

In [38]:
from numpy.random import randn, rand, randint
#bilangan distribusi uniform (0-1)
a = rand(5,4)
print(f"Ini adalah distribusi unoform : {a}" )

#bilangan gaussian => distribusi normal
b = randn(10,5)
print(f"Ini adalah Distribusi normal : {b}")

#bilangan acak dengan integer
c = randint(0,10,9)
print(f"Ini adalah Distribusi int : {c}")

#Mengubah matrisx dari 1 dimensi menjadi 2
d = c.reshape(3,3)
print(f"Ini Mengubah matrix satu dimensi menjadi 2 : {d}")

#Mencari angka max dan min 
max = d.max()
min = d.min()

print(f"Nilai tertinggi adalah : {max}")
print(f"Nilai terendah adalah : {min}")

#Mengembalikan index terbsar dan terkecil dan juga mengurutkan
argmax = d.argmax()
argmin = d.argmin()
argsort = d.argsort()
print(f"Index angka terbsesar : {argmax}")
print(f"Index angka terkecil : {argmin}")
print(f"Pengurutan angka : {argsort}")







Ini adalah distribusi unoform : [[0.76744524 0.35751133 0.73579625 0.29948499]
 [0.13330392 0.86015888 0.92567452 0.23932912]
 [0.6790867  0.55686361 0.2466808  0.50386429]
 [0.82221937 0.87610898 0.69598601 0.41088311]
 [0.24748277 0.48738216 0.60349138 0.08726161]]
Ini adalah Distribusi normal : [[ 0.90471476  0.02920057  3.42879172  1.80574061  0.98085892]
 [ 0.26498464 -0.80338153 -1.10050744  1.1606851   0.44671057]
 [-0.02569067  0.00757529  0.72159332  0.60462515  1.10669208]
 [ 1.0237956   1.29033812  0.93702103 -0.13830547 -1.49188276]
 [ 0.41090362 -0.15856608 -0.33909873  1.77443338  0.43253368]
 [ 0.70081371  0.17544541 -0.5093227   0.35186994 -0.90937957]
 [ 0.92308836  0.5757681   0.09647364  0.06509734 -1.29122309]
 [ 0.35488906 -0.73702911 -0.33033509  0.40199903 -0.32418479]
 [-0.05193612  0.97130149 -0.78000752 -0.32674885 -0.78274994]
 [-0.41820575  1.43757766  0.18683919  0.31834424 -1.85890306]]
Ini adalah Distribusi int : [6 0 6 2 5 4 5 9 6]
Ini Mengubah matrix sa

In [54]:
#Pemanggilan index => Slicing
satu = randint(0, 15,9 )
dua = satu.reshape(3,3)
print(dua)
print(dua[1,1:])

#Slicing dengan boolean di NumpY
print(dua>9)



[[ 7 14  4]
 [11  0 10]
 [ 2  9 10]]
[ 0 10]
[[False  True False]
 [ True False  True]
 [False False  True]]


In [72]:
import numpy as np

# Operasi di Numpy

# Soal Pertama
print("=================================================")
arr = np.array([10, 20, 30, 40, 50])
print(arr * 2)
print(arr - 5)
print(arr ** 2)
print(arr.mean())
print(arr.min())
print(arr.max())
print("=================================================")
print("=================================================")

# Soal Kedua 
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
print(A + B)
print(A - B)
print(A * B)
print(np.dot(A, B))
print(A.T)
print("=================================================")
print("=================================================")
# Soal Ketiga
ap = np.array([5, 10, 15, 20, 25, 30, 35, 40])
baru = []
genap = []
for i in range(len(ap)):
    if ap[i] > 20:
        baru.append(ap[i])

arbaru = np.array(baru)
print(arbaru)

for i in range(len(ap)):
    if (ap[i] % 2) == 0:
        genap.append(ap[i])

print(np.array(genap))

for i in range(len(ap)):
    if ap[i] < 15:
        ap[i] = 0
print(ap)
print("=================================================")
print("=================================================")


[ 20  40  60  80 100]
[ 5 15 25 35 45]
[ 100  400  900 1600 2500]
30.0
10
50
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[25 30 35 40]
[10 20 30 40]
[ 0  0 15 20 25 30 35 40]


In [28]:
import numpy as np
#Soal Keemapat
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(f"Rata Rata dari matrix tersebut : {data.mean()}")

for i in range(len(data[:])):
        print(f"Baris ke-{i+1} rata-rata: {np.mean(data[i])}")

for j in range(len(data[:])):
        print(f"Kolom ke-{j+1} jumlah : {np.sum(data[:, j])}")

print(f"Elemen maximumnya adalah : {data.max()} dan pada index ke-{data.argmax()}")

#Soal Kelima
arr = np.array([50, 20, 70, 10, 90, 30, 60])
print(f"Pengurutan array secara ascending : {np.sort(arr[::1])}")
print(f"Pengurutan array secara descending : {np.sort(arr[::-1])}")
print(f"Elemen array yang terbesar: {np.max(arr)} dan Elemen array index terkecil : {np.min(arr)}")








Rata Rata dari matrix tersebut : 5.0
Baris ke-1 rata-rata: 2.0
Baris ke-2 rata-rata: 5.0
Baris ke-3 rata-rata: 8.0
Kolom ke-1 jumlah : 12
Kolom ke-2 jumlah : 15
Kolom ke-3 jumlah : 18
Elemen maximumnya adalah : 9 dan pada index ke-8
Pengurutan array secara ascending : [10 20 30 50 60 70 90]
Pengurutan array secara descending : [10 20 30 50 60 70 90]
Elemen array yang terbesar: 90 dan Elemen array index terkecil : 10


PANDAS

In [12]:
import pandas as pd

# Membaca data dari excel
data = pd.read_excel("jumlah-anggaran-apbn-2024.xlsx", sheet_name=' Anggaran-kabkota')

# # Menampilkan data paling akhir urutan kelima
# print(f"Membaca data paling akhir urutan kelima :\n{data.tail(5)}")

# # Menampilkan semua data
# print(f"Membaca semua data : \n{data}")

# Melakukan sorting berdasarkan nilai PAGU > 10.000.000
for i in range(len(data)):
    if data['PAGU'][i] > 100:
        print(data.iloc[i].to_string(index=False))



   01 DKI JAKARTA
01 00 DKI JAKARTA
   52049668124000
          01 DKI JAKARTA
01 51 KOTA JAKARTA PUSAT
         329474392308000
          01 DKI JAKARTA
01 52 KOTA JAKARTA UTARA
           4415607228000
          01 DKI JAKARTA
01 53 KOTA JAKARTA BARAT
           4997506878000
            01 DKI JAKARTA
01 54 KOTA JAKARTA SELATAN
           170023682638000
          01 DKI JAKARTA
01 55 KOTA JAKARTA TIMUR
          33760086083000
        01 DKI JAKARTA
01 56 KEPULAUAN SERIBU
           73399515000
      01 DKI JAKARTA
01 99 INSTANSI PUSAT
        723340864000
   02 JAWA BARAT
02 00 JAWA BARAT
   3316965552000
   02 JAWA BARAT
02 05 KAB. BOGOR
   4530368925000
      02 JAWA BARAT
02 06 KAB. SUKABUMI
       654219785000
     02 JAWA BARAT
02 07 KAB. CIANJUR
      822897121000
    02 JAWA BARAT
02 08 KAB. BEKASI
    1118292302000
      02 JAWA BARAT
02 09 KAB. KARAWANG
       958957501000
        02 JAWA BARAT
02 10 KAB. PURWAKARTA
         475019911000
    02 JAWA BARAT
02 11 KAB. SUBAN

In [1]:
#Membaca data dari html
import pandas as pd
bank = pd.read_html("https://www.fdic.gov/bank-failures/failed-bank-list")
print(bank[0])


                               Bank Name               City          State  \
0     The First National Bank of Lindsay            Lindsay       Oklahoma   
1  Republic First Bank dba Republic Bank       Philadelphia   Pennsylvania   
2                          Citizens Bank           Sac City           Iowa   
3               Heartland Tri-State Bank            Elkhart         Kansas   
4                    First Republic Bank      San Francisco     California   
5                         Signature Bank           New York       New York   
6                    Silicon Valley Bank        Santa Clara     California   
7                      Almena State Bank             Almena         Kansas   
8             First City Bank of Florida  Fort Walton Beach        Florida   
9                   The First State Bank      Barboursville  West Virginia   

    Cert                 Aquiring Institution      Closing Date  \
0   4134   First Bank & Trust Co., Duncan, OK  October 18, 2024   
1  2733

In [51]:
import pandas as pd

# Membaca data dari file Excel
mhs = pd.read_excel("data-mahasiswa.xlsx")

# Mencetak header terlebih dahulu
print("Nama\t\tJurusan\t\t\tJenis Kelamin\tDomisili Negara")
print("-" * 80)  # Garis pemisah agar terlihat lebih rapi

# Menampilkan data mahasiswa berdasarkan jenis kelamin
laki_laki = mhs[mhs["Jenis Kelamin"] == "Laki-laki"]
perempuan = mhs[mhs["Jenis Kelamin"] == "Perempuan"]

# Mencetak data laki-laki
print("Data Laki-laki:")
for i in range(len(laki_laki)):
    print(f"{laki_laki['Nama'].iloc[i]}\t{laki_laki['Jurusan'].iloc[i]}\t{laki_laki['Jenis Kelamin'].iloc[i]}\t{laki_laki['Domisili Negara'].iloc[i]}")

print("-" * 80)

# Mencetak data perempuan
print("Data Perempuan:")
for i in range(len(perempuan)):
    print(f"{perempuan['Nama'].iloc[i]}\t{perempuan['Jurusan'].iloc[i]}\t{perempuan['Jenis Kelamin'].iloc[i]}\t{perempuan['Domisili Negara'].iloc[i]}")

print("-" * 80)

#Menampilkan jurusan saintek laki laki atau perempuan
saintek = [
    "Teknik Informatika",
    "Sistem Informasi",
    "Ilmu Komputer",
    "Teknik Elektro",
    "Teknik Mesin",
    "Teknik Sipil",
    "Teknik Kimia",
    "Teknik Industri",
    "Teknik Lingkungan",
    "Fisika",
    "Matematika",
    "Bioteknologi",
    "Kimia",
    "Astronomi",
    "Ilmu Geologi",
    "Ilmu Kesehatan Masyarakat",
    "Pendidikan Dokter",
    "Keperawatan",
    "Farmasi",
    "Kedokteran Gigi",
    "Ilmu Biologi",
    "Pendidikan Kimia",
    "Pendidikan Matematika",
    "Statistika",
    "Desain Komunikasi Visual",
    "Teknologi Pangan",
    "Ilmu Lingkungan",
    "Teknologi Informasi dan Komunikasi (TIK)",
    "Rekayasa Infrastruktur",
    "Teknologi Komunikasi"
]
saintek_cowk = 0
saintek_cewk = 0

for i in range(len(mhs)):
    for j in range(len(saintek)):
        if mhs["Jurusan"][i] == saintek[j]:
            if mhs["Jenis Kelamin"][i] == "Laki-laki":
                saintek_cowk += 1
            elif mhs["Jenis Kelamin"][i] == "Perempuan":
                saintek_cewk += 1
#Menampilkan WNI atau WNA
wni = 0
wna = 0
for i in range(len(mhs)):
    if mhs["Domisili Negara"][i] == "Indonesia":
        wni += 1
    else:
        wna += 1

# Menampilkan hasil perhitungan
print(f"Jumlah Laki-laki di jurusan Saintek: {saintek_cowk}")
print(f"Jumlah Perempuan di jurusan Saintek: {saintek_cewk}")

        

# Menampilkan perbandingan jumlah Laki-laki dan Perempuan
jumlah_laki_laki = len(laki_laki)
jumlah_perempuan = len(perempuan)

print(f"Jumlah Laki-laki: {jumlah_laki_laki}")
print(f"Jumlah Perempuan: {jumlah_perempuan}")

# Membuat perbandingan dalam bentuk persentase
total_mhs = len(mhs)
persentase_laki_laki = (jumlah_laki_laki / total_mhs) * 100
persentase_perempuan = (jumlah_perempuan / total_mhs) * 100

print(f"Persentase Laki-laki: {persentase_laki_laki:.2f}%")
print(f"Persentase Perempuan: {persentase_perempuan:.2f}%")
print(f"Jurusan Saintek yang diambil cowok : {saintek_cowk}")
print(f"Jurusan Saintek yang diambil cewek : {saintek_cewk}")
if wni > wna :
    print(f"Mahasiswa kebanyakan berwarga negara Indonesia dengan persentase : {((wni / total_mhs) * 100):.2f}%")
else:
    print(f"Mahasiswa kebanyakan berwarga negara asing dengan persentase : {((wna / total_mhs) * 100):.2f}%")




Nama		Jurusan			Jenis Kelamin	Domisili Negara
--------------------------------------------------------------------------------
Data Laki-laki:
Andi Pratama	Teknik Informatika	Laki-laki	Indonesia
Budi Santoso	Manajemen	Laki-laki	Indonesia
Joko Setiawan	Sistem Informasi	Laki-laki	Indonesia
Iwan Kurniawan	Ilmu Komputer	Laki-laki	Indonesia
Bayu Kurniawan	Teknik Mesin	Laki-laki	Thailand
Rama Prabowo	Teknik Elektro	Laki-laki	Indonesia
Rudi Hartono	Teknik Kimia	Laki-laki	Jepang
Dimas Ardiansyah	Ekonomi	Laki-laki	Indonesia
Sandi Prabowo	Teknik Sipil	Laki-laki	Indonesia
Arya Wijaya	Fisika	Laki-laki	Indonesia
--------------------------------------------------------------------------------
Data Perempuan:
Siti Rahmawati	Akuntansi	Perempuan	Indonesia
Dewi Suryani	Hukum	Perempuan	Malaysia
Ayu Lestari	Psikologi	Perempuan	Singapura
Melyna Rahmawati	Pendidikan Dokter	Perempuan	Indonesia
Nia Anggraini	Desain Komunikasi Visual	Perempuan	Indonesia
Fitria Sari	Bioteknologi	Perempuan	Filipina
Gita Maulani	